artifact_uri: file:C:/Users/bahti/Desktop/Goruntuisleme/runs/mlflow/624632983661181692/687d671929b74824bcaa877cfa6e7498/artifacts
end_time: null
entry_point_name: ''
experiment_id: '624632983661181692'
lifecycle_stage: active
run_id: 687d671929b74824bcaa877cfa6e7498
run_name: smoke_phase1
source_name: ''
source_type: 4
source_version: ''
start_time: 1773075644011
status: 1
tags: []
user_id: BahtiyarSelimDogus
